### ISSUE TITLE
Incorrect pronunciation of 3 times

### ISSUE THREAD

**Issue by shivajimutkule** [sameermahajan/PaadasMLFlaskApp#10]
It is pronounced as "Ek"

Exact File: PaadasMLFlaskApp/times/3.wav

**Comment by sameermahajan** [comment]
Thanks for catching this @shivajimutkule I also noticed it and even tried fixing it a couple of times without luck :( Trying it again. Let's see whether the fix persists.

**Comment by sameermahajan** [comment]
uploaded correct pronunciation
